import type { Metadata } from "next";
import "../styles/global.scss";
import Header from "./components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="home-tarefas-desktop">
        <Header />
        {children}
      </body>
    </html>
  );
}
